import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";

// global css
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AntdRegistry>
          <Layout>
            <Navbar />
            {children}
            <Footer />
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
