import { Categories, Layout } from "@/components";
import Navbar from "@/components/Navbar/Navbar";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

// global css
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "./globals.scss";

const montserrat = Montserrat({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Lap4All",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AntdRegistry>
          <Layout>
            <Navbar />
            <div className="content">
              <Categories />
              {children}
            </div>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
